import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({
  weight: ['100','200','300','400','500','600','700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={poppins.className}>
        <NextTopLoader color="#FE595E" height={3} showSpinner={true}/>
        {children}
      </body>
    </html>
  );
}
